apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: aws-clusters
  namespace: etherpad
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      cluster.open-cluster-management.io/clusterset: clusterset-aws

